const Invoice = require('../models/Invoice');
const Company = require('../models/Company');
const Plan = require('../models/Plan');

// @desc    Generate a new subscription invoice for a society
// @route   POST /api/superadmin/invoices
// @access  Super Admin
const generateInvoice = async (req, res) => {
    try {
        const { societyId, planId, billingPeriod } = req.body;

        const society = await Company.findById(societyId).populate('ownerId');
        if (!society) return res.status(404).json({ message: 'Society not found' });

        const plan = await Plan.findById(planId);
        if (!plan) return res.status(404).json({ message: 'Plan not found' });

        // Calculate amounts (simplified for now, ideally fetch from system settings)
        const subtotal = plan.price;
        const gstPercentage = 18;
        const gstAmount = (subtotal * gstPercentage) / 100;
        const totalAmount = subtotal + gstAmount;

        const invoice = await Invoice.create({
            societyId: society._id,
            adminId: req.user._id, // Generated by Super Admin
            customerId: society.ownerId._id, // Billed to Society Admin
            customerName: society.name,
            items: [{
                name: `Subscription Plan: ${plan.name}`,
                price: plan.price,
                quantity: 1
            }],
            type: 'Subscription',
            subtotal,
            gstPercentage,
            gstAmount,
            totalAmount,
            status: 'Pending',
            billingPeriod: {
                from: billingPeriod?.from || new Date(),
                to: billingPeriod?.to || new Date(new Date().setDate(new Date().getDate() + plan.durationDays))
            },
            dueDate: new Date(new Date().setDate(new Date().getDate() + 7)) // Due in 7 days
        });

        res.status(201).json(invoice);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server Error' });
    }
};

// @desc    Get all system invoices (Revenue tracking)
// @route   GET /api/superadmin/invoices
// @access  Super Admin
const getAllInvoices = async (req, res) => {
    try {
        const { status, page = 1, limit = 20 } = req.query;
        let query = { type: 'Subscription' };
        if (status) query.status = status;

        const invoices = await Invoice.find(query)
            .populate('societyId', 'name')
            .sort({ createdAt: -1 })
            .limit(Number(limit))
            .skip((page - 1) * limit);

        const total = await Invoice.countDocuments(query);

        res.json({
            invoices,
            page: Number(page),
            pages: Math.ceil(total / limit),
            total
        });
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server Error' });
    }
};

module.exports = { generateInvoice, getAllInvoices };
